insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Walkers Crisps', 49, 0.71, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('HP Peanuts', 97, 0.63, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Popcorn', 42, 2.53, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Pretzels', 59, 2.08, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Nachos', 63, 1.35, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Potato skins', 47, 1.26, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Beef Jerky', 33, 2.92, 'Admin', 1, 1, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Tea', 51, 1.67, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Coffee', 89, 2.21, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Pepsi Max', 88, 0.88, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Coca-Cola', 39, 0.85, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Gordons Gin', 99, 2.4, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Gin Fizz', 39, 2.56, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('White Rum', 99, 2.22, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Merlot', 25, 2.85, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Malbec', 37, 2.51, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Pinot Grigio', 39, 1.8, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Bells Whiskey', 88, 2.26, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('LemonAde', 43, 0.93, 'Admin', 1, 0, 1);
insert into pub_product (ProdName, Qty, Price, LastModifiedBy, IsAvailable, IsSnack, RestockNeeded) values ('Hot Chocolate', 94, 1.2, 'Admin', 1, 0, 1);
