DELIMITER $$
CREATE DEFINER=`ISAD251_DHirst`@`%` PROCEDURE `addAdmin`(IN `newUsername` VARCHAR(30), IN `newPassword` VARCHAR(30))
    NO SQL
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION ROLLBACK;
	DECLARE EXIT HANDLER FOR SQLWARNING ROLLBACK;
	
   START TRANSACTION;
  INSERT INTO pub_admin(Username, Password)
  VALUES (newUsername, newPassword);
  COMMIT;

END$$
DELIMITER ;