DELIMITER $$
CREATE DEFINER=`ISAD251_DHirst`@`%` PROCEDURE `addOrderDetails`(IN `oOrderID` INT, IN `oProdID` INT, IN `oQty` INT, IN `oPrice` FLOAT)
    NO SQL
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION ROLLBACK;
	DECLARE EXIT HANDLER FOR SQLWARNING ROLLBACK;
	
   START TRANSACTION;
  INSERT INTO pub_order_detail(OrderID,ProdID,Qty,Price)
  VALUES (oOrderID,oProdID,oQty,oPrice);
  COMMIT;
END$$
DELIMITER ;
